name: NGINX Load Balancer - Deploy

# This workflow can only be triggered manually
on:
  workflow_dispatch:
    branches:
        - staging
        - main

jobs:
  deploy:
    name: Deploy Tier NGINX
    # needs: tests
    runs-on: self-hosted
    steps:
      - name: Setup Environment Variables For Build Process
        run: |
          echo "DEPLOY_TIER=production" >> $GITHUB_ENV
          echo "LB_DOMAIN=core-01.vpn.otisnado.com" >> $GITHUB_ENV
          echo "SSH_PORT=22" >> $GITHUB_ENV
          echo "DEPLOY_BRANCH=main" >> $GITHUB_ENV
          echo "SWARM_SERVICE=borja_reverse_proxy" >> $GITHUB_ENV
          if [ $GITHUB_REF == 'refs/heads/staging' ]
          then
            echo "DEPLOY_TIER=staging" >> $GITHUB_ENV
            echo "DEPLOY_BRANCH=staging" >> $GITHUB_ENV
            echo "LB_DOMAIN=core-01.vpn.otisnado.com" >> $GITHUB_ENV
          fi
      - name: Deploy Update
        run: |
          export SSH_CONNECT=runner@${{ env.LB_DOMAIN }}
          ssh -o 'StrictHostKeyChecking no' -o 'PubkeyAuthentication yes' -p ${{ env.SSH_PORT }} ${SSH_CONNECT}
          ssh -p ${{ env.SSH_PORT }} ${SSH_CONNECT} "\
              cd /mnt/borja/borja-ops-nginx-loadbalancer && \
              git reset --hard HEAD && \
              git pull origin ${{ env.DEPLOY_BRANCH }} && \
              echo '==> Repository Updated!' && \
              docker service update --force ${{ env.SWARM_SERVICE }}
              "

